### ISSUE TITLE
FastAPI fails to start due to templates / views not found

### ISSUE THREAD

**Issue by prcutler** [prcutler/silversaucer#317]
If I leave @template() in home.py empty, I get this error:

```
 silversaucer> python main.py 
Traceback (most recent call last):
  File "/Users/prcutler/workspace/silversaucer/main.py", line 5, in <module>
    from views import home, play, today
  File "/Users/prcutler/workspace/silversaucer/views/home.py", line 9, in <module>
    def index():
  File "/Users/prcutler/workspace/silversaucer/testvenv/lib/python3.9/site-packages/fastapi_chameleon/engine.py", line 71, in response_inner
    if not os.path.exists(os.path.join(template_path, template_file)):
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

If I add the relative path in home.py to template() like:
`@template(home/index.pt)`

I get the error when trying to start the app:

```
 silversaucer> python main.py
Traceback (most recent call last):
  File "/Users/prcutler/workspace/silversaucer/main.py", line 5, in <module>
    from views import home, play, today
  File "/Users/prcutler/workspace/silversaucer/views/home.py", line 8, in <module>
    @template(home/index.pt)
NameError: name 'home' is not defined
```

[Main.py](https://github.com/prcutler/silversaucer/blob/fastapi/main.py) Seems to match the training course but the router isn't finding it?

**Comment by mikeckennedy** [comment]
Hi Paul, have a look over at https://github.com/mikeckennedy/fastapi-chameleon/issues/7 I just fixed the issue. Reinstall your requirements and you'll be good to go.

**Comment by prcutler** [comment]
Closed - fixed with latest version of fastapi-chameleon
